<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31158" started-at="2019-06-26T06:02:27Z" finished-at="2019-06-26T06:02:58Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:php.runner.PhpRunner$phprunner@53b32d7]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Default test" duration-ms="31158" started-at="2019-06-26T06:02:27Z" finished-at="2019-06-26T06:02:58Z">
      <class name="php.runner.PhpRunner$phprunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:php.runner.PhpRunner$phprunner@53b32d7]" name="setUpClass" is-config="true" duration-ms="166" started-at="2019-06-26T02:02:27Z" finished-at="2019-06-26T02:02:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:php.runner.PhpRunner$phprunner@53b32d7]" name="feature" duration-ms="30645" started-at="2019-06-26T02:02:28Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2019-06-26T02:02:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Phptravels Login Feature]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[junit.framework.AssertionFailedError: expected:<My Account> but was:<false>]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: junit.framework.AssertionFailedError: expected:<My Account> but was:<false>
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: junit.framework.AssertionFailedError: expected:<My Account> but was:<false>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:74)
	at php.stepdef.PhpLoginStepDef.i_should_be_able_to_login(PhpLoginStepDef.java:33)
	at âœ½.Then I should be able to login(LoginTest.feature:9)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="writeExtentReport()[pri:0, instance:php.runner.PhpRunner$phprunner@53b32d7]" name="writeExtentReport" is-config="true" duration-ms="15" started-at="2019-06-26T02:02:58Z" finished-at="2019-06-26T02:02:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeExtentReport -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:php.runner.PhpRunner$phprunner@53b32d7]" name="tearDownClass" is-config="true" duration-ms="260" started-at="2019-06-26T02:02:58Z" finished-at="2019-06-26T02:02:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- php.runner.PhpRunner$phprunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
